version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: pgdb
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - pgecommerce

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:7.8
    ports:
      - "8080:80"
    environment:
      PGADMIN_HOST: db
      PGADMIN_USER: ${PGADMIN_USER}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD} 
    networks:
      - pgecommerce

  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
    networks:
      - pgecommerce

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis
    ports:
      - 8081:8081
    networks:
      - pgecommerce

volumes:
  pgdb:
    external: false
  redisdata:
    external: false

networks:
  pgecommerce:
    driver: bridge